services:
  - type: web
    name: doodlesphere
    env: node
    rootDir: doodlesphere-backend
    buildCommand: npm install
    startCommand: node api/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"e
    healthCheckPath: /health
    autoDeploy: true