services:
  - type: web
    name: doodlesphere-backend
    env: node
    rootDir: doodlesphere-backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    routes:
      - type: http
        path: /health
    healthCheckPath: /health
    autoDeploy: true