services:
  - type: web
    name: doodlesphere-backend
    env: node
    rootDir: doodlesphere-backend
    buildCommand: npm install
    startCommand: node api/index.js
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /health