services:
  - type: web
    name: doodlesphere-backend
    env: node
    rootDir: doodlesphere-backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
    healthCheckPath: /health
    autoDeploy: true